version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: ["pnpm", "start"]
    restart: unless-stopped
